remote_theme: pmarsceill/just-the-docs

title: ssa.rajniti.online
highlighter: rouge
permalink: /:title/
year: 2020
description: Sarv Siksha Abhiyan
url: https://ssa.rajniti.online
encoding: UTF-8

paginate: 6
paginate_path: /page/:num/

plugins:
  - jekyll-seo-tag
  
compress_html:
clippings: all
comments: all
endings: all
startings: []
blanklines: false
profile: false

# Google Analytics Tracking
ga_tracking: UA-139531653-4
